version: "3"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./backend/
    restart: always
    environment:
      - PORT=8000
      - MONGODB_URL=mongodb://mongodb:27017/relationship-builder
    ports:
      - "8000:8000" 
    volumes:
      - /usr/src/backendapp
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/src/frontendapp
    depends_on:
      - backend
